name: Keep Render Alive (Optimized)

on:
  schedule:
    - cron: "*/15 4-11 * * 1-5"  # Runs every 15 mins from 10 AM - 6 PM IST (UTC 4:00 - 11:59)
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render App
        run: curl -s -o /dev/null -w "%{http_code}" https://codewizards-7i7p.onrender.com
